# Generated by Django 5.2.5 on 2025-08-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orders",
            name="status",
        ),
        migrations.AlterField(
            model_name="category",
            name="category_name",
            field=models.CharField(
                choices=[
                    ("acoustic guitars", "Акустические гитары"),
                    ("electric guitars", "Электро гитары"),
                    ("classic guitars", "Классические гитары"),
                    ("bass guitars", "Бас гитары"),
                    ("acoustic bass guitars", "Акустические бас гитары"),
                    ("strings", "Струны"),
                ],
                max_length=21,
            ),
        ),
    ]
